// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by scripts/generate-abi-constants.js from the ffigen bindings.
// Do not edit; run the script after ffigen.

// ignore_for_file: constant_identifier_names

const int AUD_ABI_VERSION_MAJOR = 0;
const int AUD_ABI_VERSION_MINOR = 3;
const int AUD_ARG_FALSE = 70;
const int AUD_ARG_FLOAT = 102;
const int AUD_ARG_IMPULSE = 73;
const int AUD_ARG_INT32 = 105;
const int AUD_ARG_NIL = 78;
const int AUD_ARG_TRUE = 84;
const int AUD_BEAT_FACTOR = 2147483648;
const int AUD_BUS_MAIN = 1;
const int AUD_BUS_OPTIONAL = 4;
const int AUD_BUS_SIDECHAIN = 2;
const int AUD_CORE_GAIN_PARAM_GAIN = 0;
const int AUD_CORE_GAIN_STATE_VERSION = 1;
const String AUD_CORE_GAIN_TYPE_ID = 'aud.core.gain';
const int AUD_ERROR_ABI_MAJOR = -2;
const int AUD_ERROR_ABI_MINOR = -3;
const int AUD_ERROR_BUFFER_TOO_SMALL = -11;
const int AUD_ERROR_CAPACITY = -18;
const int AUD_ERROR_CYCLE = -15;
const int AUD_ERROR_DUPLICATE_TYPE = -4;
const int AUD_ERROR_FAILED = -9;
const int AUD_ERROR_FORMAT = -16;
const int AUD_ERROR_INVALID_ARGUMENT = -1;
const int AUD_ERROR_LATE = -13;
const int AUD_ERROR_LOOKAHEAD = -17;
const int AUD_ERROR_NOT_FOUND = -14;
const int AUD_ERROR_OUT_OF_MEMORY = -7;
const int AUD_ERROR_OVERLOAD = -20;
const int AUD_ERROR_QUEUE_FULL = -6;
const int AUD_ERROR_RETIRED = -19;
const int AUD_ERROR_STATE = -8;
const int AUD_ERROR_STATE_VERSION = -12;
const int AUD_ERROR_UNKNOWN_TYPE = -5;
const int AUD_ERROR_UNSUPPORTED = -10;
const int AUD_EVENT_CONTROL = 2;
const int AUD_EVENT_FLAG_LIVE = 1;
const int AUD_EVENT_PARAM = 3;
const int AUD_EVENT_PORT_CONTROL = 2;
const int AUD_EVENT_PORT_MIDI = 1;
const int AUD_EVENT_UMP = 1;
const int AUD_LOG_DEBUG = 0;
const int AUD_LOG_ERROR = 3;
const int AUD_LOG_INFO = 1;
const int AUD_LOG_WARNING = 2;
const int AUD_NODE_CAP_EVENTS = 4;
const int AUD_NODE_CAP_EVENT_OUTPUT = 256;
const int AUD_NODE_CAP_IN_PLACE = 1;
const int AUD_NODE_CAP_LATENCY = 32;
const int AUD_NODE_CAP_RESET_ON_SEEK = 1024;
const int AUD_NODE_CAP_RESET_ON_STOP = 512;
const int AUD_NODE_CAP_STATE = 16;
const int AUD_NODE_CAP_STRINGS = 8;
const int AUD_NODE_CAP_TAIL = 64;
const int AUD_NODE_CAP_TRANSPORT = 128;
const int AUD_NODE_CAP_VARIABLE_BLOCK = 2;
const int AUD_OK = 0;
const int AUD_PARAM_AUTOMATABLE = 1;
const int AUD_PARAM_BOOLEAN = 16;
const int AUD_PARAM_HIDDEN = 32;
const int AUD_PARAM_LOGARITHMIC = 8;
const int AUD_PARAM_RAMPED = 2;
const int AUD_PARAM_STEPPED = 4;
const int AUD_PENDING = 1;
const int AUD_PROCESS_OFFLINE = 1;
const int AUD_RESET_PREPARE = 2;
const int AUD_RESET_RECOVERY = 3;
const int AUD_RESET_SEEK = 1;
const int AUD_RESET_STOP = 0;
const int AUD_SEGMENT_DISCONTINUITY = 8;
const int AUD_SEGMENT_LOOPING = 2;
const int AUD_SEGMENT_PLAYING = 1;
const int AUD_SEGMENT_SEEK = 4;
const int AUD_TAIL_INFINITE = 4294967295;
const int AUD_THREAD_CONTROL = 0;
const int AUD_THREAD_OFFLINE = 2;
const int AUD_THREAD_REALTIME = 1;
const int AUD_TIME_BEAT = 3;
const int AUD_TIME_HOST = 2;
const int AUD_TIME_IMMEDIATE = 0;
const int AUD_TIME_SAMPLE = 1;
const int AUD_TIME_SOURCE_ESTIMATED = 2;
const int AUD_TIME_SOURCE_HARDWARE = 1;
const int AUD_TIME_SOURCE_NONE = 0;
const int AUD_TIME_SOURCE_SYNTHESIZED = 3;
const int AUD_TRANSPORT_CAP_HOST_TIME = 16;
const int AUD_TRANSPORT_CAP_LOOP = 32;
const int AUD_TRANSPORT_CAP_SEEK = 2;
const int AUD_TRANSPORT_CAP_START_STOP = 4;
const int AUD_TRANSPORT_CAP_TEMPO = 1;
const int AUD_TRANSPORT_CAP_TIME_SIGNATURE = 8;
const int AUD_TRANSPORT_REQUEST_SEEK = 3;
const int AUD_TRANSPORT_REQUEST_SET_LOOP = 6;
const int AUD_TRANSPORT_REQUEST_SET_QUANTUM = 7;
const int AUD_TRANSPORT_REQUEST_SET_TEMPO = 4;
const int AUD_TRANSPORT_REQUEST_SET_TIME_SIGNATURE = 5;
const int AUD_TRANSPORT_REQUEST_START = 1;
const int AUD_TRANSPORT_REQUEST_STOP = 2;
