// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by ffigen; the struct helpers it emits are not exercised.
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// sizeof the ABI structs as the C compiler lays them out.
@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_sizeof_event();

@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_sizeof_host_api();

@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_sizeof_node_descriptor();

@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_sizeof_node_vtable();

@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_sizeof_param_descriptor();

@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_sizeof_process_context();

/// The major ABI version compiled into the native core.
@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_version_major();

/// The minor ABI version compiled into the native core.
@ffi.Native<ffi.Int32 Function()>()
external int aud_abi_version_minor();

const int AUD_ABI_VERSION_MAJOR = 0;

const int AUD_ABI_VERSION_MINOR = 1;

const int AUD_ERROR_ABI_MAJOR = -2;

const int AUD_ERROR_ABI_MINOR = -3;

const int AUD_ERROR_DUPLICATE_TYPE = -4;

const int AUD_ERROR_FAILED = -9;

const int AUD_ERROR_INVALID_ARGUMENT = -1;

const int AUD_ERROR_OUT_OF_MEMORY = -7;

const int AUD_ERROR_QUEUE_FULL = -6;

const int AUD_ERROR_STATE = -8;

const int AUD_ERROR_UNKNOWN_TYPE = -5;

const int AUD_EVENT_CONTROL = 3;

const int AUD_EVENT_NOTE_OFF = 2;

const int AUD_EVENT_NOTE_ON = 1;

const int AUD_LOG_DEBUG = 0;

const int AUD_LOG_ERROR = 3;

const int AUD_LOG_INFO = 1;

const int AUD_LOG_WARNING = 2;

const int AUD_NODE_CAP_EVENTS = 4;

const int AUD_NODE_CAP_IN_PLACE = 1;

const int AUD_NODE_CAP_STRINGS = 8;

const int AUD_NODE_CAP_VARIABLE_BLOCK = 2;

const int AUD_OK = 0;

const int AUD_THREAD_CONTROL = 0;

const int AUD_THREAD_REALTIME = 1;

/// An event delivered to a node before the block it belongs to.
final class AudEvent extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_EVENT_*
  @ffi.Uint32()
  external int type;

  /// offset inside the block; the spike applies 0
  @ffi.Uint32()
  external int sample_offset;

  /// MIDI channel 0..15
  @ffi.Uint32()
  external int channel;

  /// note number or controller number
  @ffi.Uint32()
  external int number;

  /// velocity 0..1 or controller value
  @ffi.Float()
  external double value;

  static ffi.Pointer<AudEvent> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int type,
    required int sample_offset,
    required int channel,
    required int number,
    required double value,
  }) => $allocator<AudEvent>()
    ..ref.struct_size = struct_size
    ..ref.type = type
    ..ref.sample_offset = sample_offset
    ..ref.channel = channel
    ..ref.number = number
    ..ref.value = value;
}

/// What the engine offers a package. Memory crossing the ABI is owned by the
/// engine's allocator.
final class AudHostApi extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// the engine's ABI
  @ffi.Uint32()
  external int abi_major;

  @ffi.Uint32()
  external int abi_minor;

  /// opaque engine handle, passed back to every callback
  external ffi.Pointer<ffi.Void> host;

  /// [control] Registers a node type; AUD_OK or an error code.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<ffi.Void> host,
        ffi.Pointer<AudNodeDescriptor> descriptor,
      )
    >
  >
  register_node_type;

  /// [control] Allocates memory for non-realtime work.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void> host, ffi.Size bytes)
    >
  >
  alloc;

  /// [control] Frees memory from alloc.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> host,
        ffi.Pointer<ffi.Void> memory,
      )
    >
  >
  free;

  /// [control] Logs a message; never called on the realtime thread.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> host,
        ffi.Int32 level,
        ffi.Pointer<ffi.Char> message,
      )
    >
  >
  log;

  static ffi.Pointer<AudHostApi> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int abi_major,
    required int abi_minor,
    required ffi.Pointer<ffi.Void> host,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<ffi.Void> host,
          ffi.Pointer<AudNodeDescriptor> descriptor,
        )
      >
    >
    register_node_type,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Void> host,
          ffi.Size bytes,
        )
      >
    >
    alloc,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> host,
          ffi.Pointer<ffi.Void> memory,
        )
      >
    >
    free,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> host,
          ffi.Int32 level,
          ffi.Pointer<ffi.Char> message,
        )
      >
    >
    log,
  }) => $allocator<AudHostApi>()
    ..ref.struct_size = struct_size
    ..ref.abi_major = abi_major
    ..ref.abi_minor = abi_minor
    ..ref.host = host
    ..ref.register_node_type = register_node_type
    ..ref.alloc = alloc
    ..ref.free = free
    ..ref.log = log;
}

/// A node type a package registers.
final class AudNodeDescriptor extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// the ABI the package was built against
  @ffi.Uint32()
  external int abi_major;

  @ffi.Uint32()
  external int abi_minor;

  /// e.g. "aud.effects.tremolo"
  external ffi.Pointer<ffi.Char> type_id;

  /// display name
  external ffi.Pointer<ffi.Char> name;

  /// AUD_NODE_CAP_* flags
  @ffi.Uint32()
  external int capabilities;

  /// audio buses; 0 or 1 in the spike
  @ffi.Uint32()
  external int num_inputs;

  /// audio buses; 1 in the spike
  @ffi.Uint32()
  external int num_outputs;

  @ffi.Uint32()
  external int num_params;

  external ffi.Pointer<AudParamDescriptor> params;

  external ffi.Pointer<AudNodeVTable> vtable;

  static ffi.Pointer<AudNodeDescriptor> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int abi_major,
    required int abi_minor,
    required ffi.Pointer<ffi.Char> type_id,
    required ffi.Pointer<ffi.Char> name,
    required int capabilities,
    required int num_inputs,
    required int num_outputs,
    required int num_params,
    required ffi.Pointer<AudParamDescriptor> params,
    required ffi.Pointer<AudNodeVTable> vtable,
  }) => $allocator<AudNodeDescriptor>()
    ..ref.struct_size = struct_size
    ..ref.abi_major = abi_major
    ..ref.abi_minor = abi_minor
    ..ref.type_id = type_id
    ..ref.name = name
    ..ref.capabilities = capabilities
    ..ref.num_inputs = num_inputs
    ..ref.num_outputs = num_outputs
    ..ref.num_params = num_params
    ..ref.params = params
    ..ref.vtable = vtable;
}

/// The functions of a node type. The tag in brackets names the calling
/// thread.
final class AudNodeVTable extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// [control] Creates an instance; returns NULL on failure.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<AudNodeDescriptor> descriptor,
        ffi.Pointer<AudHostApi> host,
      )
    >
  >
  create;

  /// [control] Destroys an instance.
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> instance)>
  >
  destroy;

  /// [control] Prepares the instance for a sample rate, a largest block and a
  /// channel count; called before the first process call and on every change.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<ffi.Void> instance,
        ffi.Double sample_rate,
        ffi.Uint32 max_frames,
        ffi.Uint32 channels,
      )
    >
  >
  prepare;

  /// [realtime] Resets the state (stop, seek).
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> instance)>
  >
  reset;

  /// [realtime] Sets a parameter by its index in the descriptor.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> instance,
        ffi.Uint32 param_index,
        ffi.Float value,
      )
    >
  >
  set_param;

  /// [realtime] Delivers an event; NULL unless AUD_NODE_CAP_EVENTS is set.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> instance,
        ffi.Pointer<AudEvent> event,
      )
    >
  >
  event;

  /// [realtime] Renders one block; no allocation, no lock, no I/O.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> instance,
        ffi.Pointer<AudProcessContext> context,
      )
    >
  >
  process;

  /// [control] Applies a string setting; NULL unless AUD_NODE_CAP_STRINGS is
  /// set. May block.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<ffi.Void> instance,
        ffi.Uint32 key,
        ffi.Pointer<ffi.Char> value,
      )
    >
  >
  set_string;

  static ffi.Pointer<AudNodeVTable> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<AudNodeDescriptor> descriptor,
          ffi.Pointer<AudHostApi> host,
        )
      >
    >
    create,
    required ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> instance)>
    >
    destroy,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<ffi.Void> instance,
          ffi.Double sample_rate,
          ffi.Uint32 max_frames,
          ffi.Uint32 channels,
        )
      >
    >
    prepare,
    required ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> instance)>
    >
    reset,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> instance,
          ffi.Uint32 param_index,
          ffi.Float value,
        )
      >
    >
    set_param,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> instance,
          ffi.Pointer<AudEvent> event,
        )
      >
    >
    event,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> instance,
          ffi.Pointer<AudProcessContext> context,
        )
      >
    >
    process,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int32 Function(
          ffi.Pointer<ffi.Void> instance,
          ffi.Uint32 key,
          ffi.Pointer<ffi.Char> value,
        )
      >
    >
    set_string,
  }) => $allocator<AudNodeVTable>()
    ..ref.struct_size = struct_size
    ..ref.create = create
    ..ref.destroy = destroy
    ..ref.prepare = prepare
    ..ref.reset = reset
    ..ref.set_param = set_param
    ..ref.event = event
    ..ref.process = process
    ..ref.set_string = set_string;
}

/// A parameter of a node type.
final class AudParamDescriptor extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// stable identifier, e.g. "frequency"
  external ffi.Pointer<ffi.Char> id;

  /// display name
  external ffi.Pointer<ffi.Char> name;

  /// "Hz", "dB" or ""
  external ffi.Pointer<ffi.Char> unit;

  @ffi.Float()
  external double min_value;

  @ffi.Float()
  external double max_value;

  @ffi.Float()
  external double default_value;

  static ffi.Pointer<AudParamDescriptor> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required ffi.Pointer<ffi.Char> id,
    required ffi.Pointer<ffi.Char> name,
    required ffi.Pointer<ffi.Char> unit,
    required double min_value,
    required double max_value,
    required double default_value,
  }) => $allocator<AudParamDescriptor>()
    ..ref.struct_size = struct_size
    ..ref.id = id
    ..ref.name = name
    ..ref.unit = unit
    ..ref.min_value = min_value
    ..ref.max_value = max_value
    ..ref.default_value = default_value;
}

/// The block a node renders. Buses are planar: one float array per channel.
final class AudProcessContext extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// frames in this block, at most the prepared maximum
  @ffi.Uint32()
  external int frames;

  /// channels per bus
  @ffi.Uint32()
  external int channels;

  @ffi.Double()
  external double sample_rate;

  /// input bus; NULL for a source node
  external ffi.Pointer<ffi.Pointer<ffi.Float>> inputs;

  /// output bus
  external ffi.Pointer<ffi.Pointer<ffi.Float>> outputs;

  static ffi.Pointer<AudProcessContext> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int frames,
    required int channels,
    required double sample_rate,
    required ffi.Pointer<ffi.Pointer<ffi.Float>> inputs,
    required ffi.Pointer<ffi.Pointer<ffi.Float>> outputs,
  }) => $allocator<AudProcessContext>()
    ..ref.struct_size = struct_size
    ..ref.frames = frames
    ..ref.channels = channels
    ..ref.sample_rate = sample_rate
    ..ref.inputs = inputs
    ..ref.outputs = outputs;
}

/// The signature of the registration entry point every DSP package exports
/// as `int32_t aud_<package>_register(const AudHostApi* host)`.
typedef AudRegisterFunction =
    ffi.Pointer<ffi.NativeFunction<AudRegisterFunctionFunction>>;
typedef AudRegisterFunctionFunction =
    ffi.Int32 Function(ffi.Pointer<AudHostApi> host);
typedef DartAudRegisterFunctionFunction =
    int Function(ffi.Pointer<AudHostApi> host);

/// [realtime] The render interface between a host of the engine and the
/// engine (plugin-002): the host supplies an interleaved output buffer, the
/// engine fills `frames` frames of `channels` channels. aud_audio_io calls
/// it from its stream callback.
typedef AudRenderCallback =
    ffi.Pointer<ffi.NativeFunction<AudRenderCallbackFunction>>;
typedef AudRenderCallbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> user,
      ffi.Pointer<ffi.Float> interleaved_output,
      ffi.Uint32 frames,
      ffi.Uint32 channels,
    );
typedef DartAudRenderCallbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> user,
      ffi.Pointer<ffi.Float> interleaved_output,
      int frames,
      int channels,
    );
